# Generated by Django 2.1.5 on 2019-01-21 17:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocoin',
            old_name='alias',
            new_name='symbol',
        ),
        migrations.RemoveField(
            model_name='cryptocoin',
            name='name',
        ),
        migrations.AddField(
            model_name='cryptocoin',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='cryptocoin',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
